src/main/scala/chisel3/tester/BackendInterface.scala
src/main/scala/chisel3/tester/TreadleBackend.scala
src/main/scala/chisel3/tester/package.scala
src/test/scala/chisel3/tests/QueueTest.scala
src/test/scala/chisel3/tests/TestUtils.scala
src/test/scala/chisel3/tests/TimeoutTest.scala

Add deadlock timeout detection and tests

---

src/main/scala/chisel3/tester/BackendInterface.scala
src/main/scala/chisel3/tester/DecoupledDriver.scala
src/main/scala/chisel3/tester/TreadleBackend.scala
src/main/scala/chisel3/tester/package.scala
src/test/scala/chisel3/tests/QueueTest.scala

Resolves #23 
Also make init*, set*Clock chainable in DecoupledDriver

Implicit clock resolution stub functions

---

src/main/scala/chisel3/tester/ThreadedBackend.scala
src/main/scala/chisel3/tester/TreadleBackend.scala

Fixes #24 
- Ensures scheduler is not reinvoked when a thread is killed by interrupt (because the scheduler state will be incorrect)
- Ensures tester.report() is invoked after a testdriver exception, so VCDs can be generated. (unclear how this may interact with Treadle exceptions, if Treadle is left in an inconsistent state)

Proper cleanup when a test fails (exception thrown in testdriver code)

---

src/main/scala/chisel3/tester/TreadleBackend.scala
src/main/scala/chisel3/tester/experimental/UncheckedClockPeek.scala
src/main/scala/chisel3/tester/internal/BackendInterface.scala
src/test/scala/chisel3/tests/ClockPeekTest.scala

This is super useful since clock poking has been implemented

Add support for clock peeking

---

src/main/scala/chisel3/tester/TreadleBackend.scala

Related to freechipsproject/firrtl#1107, which fixes freechipsproject/firrtl#1103.

Use new CombinationalPath annotation with Target API

---

src/main/scala/chisel3/tester/legacy/backends/verilator/SimApiInterface.scala

logger should be used for develop debugging.

Fixes printf's not showing up.

---

src/main/scala/chisel3/tester/ChiselScalatestTester.scala
src/main/scala/chisel3/tester/RawTester.scala
src/main/scala/chisel3/tester/backends/BackendExecutive.scala
src/main/scala/chisel3/tester/backends/treadle/TreadleBackend.scala
src/main/scala/chisel3/tester/backends/treadle/TreadleExecutive.scala
src/main/scala/chisel3/tester/defaults.scala
src/main/scala/chisel3/tester/experimental/TestOptionBuilder.scala
src/main/scala/chisel3/tester/experimental/UncheckedClockPeek.scala
src/main/scala/chisel3/tester/experimental/UncheckedClockPoke.scala
src/main/scala/chisel3/tester/internal/BackendInterface.scala
src/main/scala/chisel3/tester/internal/Testers2.scala
src/main/scala/chisel3/tester/internal/ThreadedBackend.scala
src/main/scala/chisel3/tester/legacy/backends/verilator/SimApiInterface.scala
src/main/scala/chisel3/tester/legacy/backends/verilator/VerilatorBackend.scala
src/main/scala/chisel3/tester/legacy/backends/verilator/VerilatorCppHarnessGenerator.scala
src/main/scala/chisel3/tester/legacy/backends/verilator/VerilatorExecutive.scala
src/test/scala/chisel3/experimental/tests/VerilatorClockPokeTest.scala
src/test/scala/chisel3/tests/AsyncClockTest.scala
src/test/scala/chisel3/tests/AsyncResetTest.scala
src/test/scala/chisel3/tests/ClockPeekTest.scala
src/test/scala/chisel3/tests/ClockPokeTest.scala
src/test/scala/chisel3/tests/OptionsPassingTest.scala
src/test/scala/chisel3/tests/TestUtils.scala

Support migration of dontTouch, RawModule, MultiIOModule from experimental

---

build.sbt
src/test/scala/chisel3/tests/UtestTesterTest.scala

Sorry I forget 2.11 is still supported by chisel3.

use latest utest, fix issue utest#211

---

.gitignore
src/main/scala/chisel3/tester/ValidDriver.scala
src/main/scala/chisel3/tester/package.scala
src/test/scala/chisel3/tests/ValidQueueTest.scala

Adds Valid control structure similar to Decoupled
Adds tests of new construct

Add valid io driver

---

.gitignore
README.md
build.sbt
src/main/scala/chisel3/tester/ChiselScalatestTester.scala
src/main/scala/chisel3/tester/ChiselUtestTester.scala
src/main/scala/chisel3/tester/DecoupledDriver.scala
src/main/scala/chisel3/tester/ValidDriver.scala
src/main/scala/chisel3/tester/backends/treadle/TreadleExecutive.scala
src/main/scala/chisel3/tester/experimental/TestOptionBuilder.scala
src/main/scala/chisel3/tester/package.scala
src/test/scala/chisel3/tests/BoreTest.scala
src/test/scala/chisel3/tests/BundleLiteralsSpec.scala
src/test/scala/chisel3/tests/OptionsBackwardCompatibilityTest.scala
src/test/scala/chisel3/tests/QueueTest.scala
src/test/scala/chisel3/tests/UtestTesterTest.scala
src/test/scala/chisel3/tests/ValidQueueTest.scala
src/test/scala/chisel3/tests/VecPokeExpectTest.scala

0.1.x cherrypickmaster

---

README.md

Update chiseltest version in README

---

src/main/scala/chiseltest/package.scala
src/test/scala/chiseltest/tests/BasicTest.scala
src/test/scala/chiseltest/tests/TestUtils.scala

Depends on freechipsproject/chisel3#1400. In this commit, duplex `Record` peek/poke is enabled for complex IO like
`TLBundle` or `AutoBundle`.
1. replace `litValue` with `litOption.map(v => doSometing)`, for the use
case of Record partial assignment.
2. use `elements.keys` to match `x` and `value` field, this will result
poke/except the element with same key and not `None`.
Build with: git-clone firrtl https://github.com/freechipsproject/firrtl.git master
Build with: git-clone chisel3 https://github.com/freechipsproject/chisel3.git master

Partial poke to Record data. 

---

project/.gitignore

Build with: git-clone firrtl https://github.com/freechipsproject/firrtl.git master
Build with: git-clone chisel3 https://github.com/freechipsproject/chisel3.git master

Ignore metals generated file

---

README.md
build.sbt

Build with: git-clone firrtl https://github.com/freechipsproject/firrtl.git master
Build with: git-clone chisel3 https://github.com/freechipsproject/chisel3.git master
Build with: git-clone treadle https://github.com/freechipsproject/treadle.git master

Bump SNAPSHOT version.

---

src/main/scala/chiseltest/legacy/backends/verilator/VerilatorCppHarnessGenerator.scala

Use newer flush call back api in newer version of verilator to avoid the compile error (#177).

Verilator: use newer flush call back api to support newer version of verilator

---

build.sc

This PR adds mill build system support.

add mill support

---

src/main/scala/chiseltest/legacy/backends/vcs/VcsExecutive.scala

I recently ran into an error when switching from the VerilatorBackendAnnotation to the VcsBackendAnnotation:
```
[info] TLRAMTest:
[info] - should Driver/Monitor Master Hardcoded Burst TLRAM *** FAILED ***
[info]   firrtl.options.StageError:
[info]   at chisel3.stage.ChiselStage.run(ChiselStage.scala:49)
[info]   at chiseltest.legacy.backends.vcs.VcsExecutive$.start(VcsExecutive.scala:61)
[info]   at chiseltest.defaults.package$.createDefaultTester(defaults.scala:24)
[info]   at chiseltest.ChiselScalatestTester$TestBuilder.apply(ChiselScalatestTester.scala:33)
[info]   at verif.TLRAMTest.$anonfun$new$1(TLRAMTest.scala:42)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at …
```

Fix VCS Double Elaboration Bug

---

src/main/scala/chiseltest/package.scala
src/test/scala/chiseltest/tests/ElementTest.scala

Signed-off-by: zhongzc <zhongzc_arch@outlook.com>
fix #113

peek on FixedPoint uses BigDecimal math

---

src/main/scala/chiseltest/experimental/Async.scala

fix for API change introduced in chipsalliance/treadle#290.

bug fix for treadle API changes.

---

build.sbt
build.sc
src/main/scala/chiseltest/experimental/Async.scala

for build.sbt and build.sc
version goes to 0.5
dependencies updated

Bump to next release

---

.scala-steward.conf

scala-steward: limit the frequency of PRs

---

src/main/scala/chiseltest/legacy/backends/verilator/VerilatorExecutive.scala

The caching hash files were creating in the beginning of checks. In case `CachingAnnotation` was used and there were any issues during Verilator cpp generation/build (e.g. problem with Verilator installation or version), verilator generation would never run again (after fixing the installation issue). The user needed to manually delete the previous directory or hash files.
Caching hash is consolidated into a single `caching.hash` file. Should potentially make the cached run a little faster.
Also avoids needless overwrites.

Defer creation of caching hash file

---

src/test/scala/chiseltest/backends/verilator/VerilatorCachingTests.scala

During my work on https://github.com/ucb-bar/chisel-testers2/pull/334 I realized that the current tests keep on working, even if caching is removed.
The new tests try to determine whether something is cached by measuring the relative time it takes to execute a test/. I have observed that cached tests normally execute about 2.5 times faster than uncached tests, thus I am hopeful that this won't be too brittle.

test: actually test caching

---

src/test/scala/chiseltest/backends/verilator/VerilatorCachingTests.scala

1) small warmup compilation that isn't timed
2) average differences instead of checking all of them

make caching tests more stable

---

src/test/scala/chiseltest/backends/verilator/VerilatorCachingTests.scala
src/test/scala/chiseltest/simulator/ComplianceTest.scala
src/test/scala/chiseltest/simulator/Icarus.scala
src/test/scala/chiseltest/simulator/Treadle.scala
src/test/scala/chiseltest/simulator/Vcs.scala
src/test/scala/chiseltest/simulator/Verilator.scala
src/test/scala/chiseltest/utils/CaptureStdout.scala
src/test/scala/chiseltest/utils/FlatSpecWithTargetDir.scala

pulled out from https://github.com/ucb-bar/chisel-testers2/pull/356

test: move utils into their own package

---

src/main/scala/chiseltest/simulator/VerilatorSimulator.scala
src/test/resources/iotesters/AddTwoAddThree.v
src/test/scala/chiseltest/tests/VerilogBlackBoxTests.scala

Fix from: https://github.com/ucb-bar/chisel-testers2/pull/348

verilator: fix black box includes

---

src/main/scala/chiseltest/simulator/IcarusSimulator.scala
src/main/scala/chiseltest/simulator/VcsSimulator.scala
src/main/scala/chiseltest/simulator/ipc/IPCSimulatorContext.scala
src/main/scala/chiseltest/simulator/ipc/VpiVerilogHarnessGenerator.scala
src/test/resources/init.mem
src/test/scala/chiseltest/simulator/Icarus.scala
src/test/scala/chiseltest/simulator/MemoryCompliance.scala
src/test/scala/chiseltest/simulator/Treadle.scala
src/test/scala/chiseltest/simulator/Verilator.scala

Needs: https://github.com/chipsalliance/treadle/pull/349

simulator: make sure memory loading works

---

src/main/scala/chiseltest/simulator/VerilatorSimulator.scala
src/test/resources/DualPortNewDataRAM.v
src/test/scala/chiseltest/regressions/DoohickeyTest.scala

This PR fixes the regression reported by @oharboe in https://github.com/ucb-bar/chisel-testers2/pull/315

Fix Verilator Coverage Regression

---

build.sbt
src/test/scala/chiseltest/tests/DeprecatedTest.scala

not yet to merge, needs to be tested

Use ScalaTest 3.1 for derpication warnings

---

src/main/scala/chiseltest/simulator/jna/VerilatorCppJNAHarnessGenerator.scala
src/test/scala/chiseltest/regressions/DoohickeyTest.scala
src/test/scala/chiseltest/tests/AssertTests.scala

This regression was introduced when switching to the JNA based harness. Thanks to @oharboe for reporting this bug.

Fix verilator linking error

---

build.sc

downgrade scalatest

---

README.md

The simple example need step() no ?

step() example

---

src/main/scala/chiseltest/formal/backends/DefRandToRegisterPass.scala

Previously, the registers we used to represent DefRandom nodes in treadle were constant propagated through which would result in an incorrect VCD when the bug involved arbitrary values chosen by the formal engine.

formal: fix trace replay with arbitrary values

---

src/test/scala/chiseltest/backends/verilator/VerilatorCoverageTests.scala
src/test/scala/chiseltest/coverage/SimulatorCoverageTest.scala
src/test/scala/chiseltest/coverage/Test1Module.scala
src/test/scala/chiseltest/experimental/tests/VcsCoverageTests.scala
src/test/scala/chiseltest/formal/BasicBoundedCheckTests.scala
src/test/scala/chiseltest/formal/MemoryTests.scala
src/test/scala/chiseltest/formal/ResetAssumptionTests.scala
src/test/scala/chiseltest/formal/SafePastSpec.scala
src/test/scala/chiseltest/formal/UndefinedValuesTests.scala
src/test/scala/chiseltest/formal/examples/DecoupledGCD.scala
src/test/scala/chiseltest/formal/examples/KeepMax.scala
src/test/scala/chiseltest/formal/examples/SvaDemos.scala
src/test/scala/chiseltest/formal/examples/VGBComparisonOfFormalAndSimulation.scala
src/test/scala/chiseltest/formal/examples/ZipCpuQuizzes.scala

This is in response to: https://github.com/chipsalliance/chisel3/pull/2089

test: switch away from deprecated experimental.verification package

---

src/main/scala/chiseltest/simulator/Simulator.scala
src/main/scala/chiseltest/simulator/VerilatorSimulator.scala
src/main/scala/chiseltest/simulator/jna/VerilatorCppJNAHarnessGenerator.scala
src/test/scala/chiseltest/simulator/BasicCompliance.scala
src/test/scala/chiseltest/simulator/ComplianceTest.scala
src/test/scala/chiseltest/simulator/Verilator.scala

Only print Verilator messages in verbose mode

---

.github/workflows/test.yml

let's see if this helps speed up our CI again

ci: use pre-compiled verilator from tabby

---

src/main/scala/chiseltest/exceptions.scala
src/main/scala/chiseltest/internal/GenericBackend.scala

Fixes #461 h/t @ducky64 for the idea.

Provide a suggestion in TimeoutException

---

README.md

I would be curious to here some community feedback from @carlosedp and @schoeberl as well.

update readme for 0.5 release

---

src/main/scala/chiseltest/simulator/Caching.scala
src/test/scala/chiseltest/backends/verilator/VerilatorCachingTests.scala

simulator: remove debug println from caching implementation

---

src/main/scala/chiseltest/simulator/Simulator.scala
src/main/scala/chiseltest/simulator/ipc/IPCSimulatorContext.scala
src/main/scala/chiseltest/simulator/ipc/VpiVerilogHarnessGenerator.scala
src/main/scala/chiseltest/simulator/jna/JNASimulatorContext.scala
src/main/scala/chiseltest/simulator/jna/VerilatorCppJNAHarnessGenerator.scala

simulator: better error message when circuit has multiple input clocks

---

.mergify.yml

based on jack's changes: https://github.com/chipsalliance/firrtl/pull/2454/files

update mergify config

---

.github/configs/mergify_config.yml
.github/workflows/test.yml
.mergify.yml

* Enable CI for 0.5.x branch
* Enable Mergify for 0.5.x branch
I went ahead and added the `mergify_config.yml` a la chisel3 and firrtl so that we can generate the .mergify.yml. I also have it backporting to 0.3.x and 0.5.x but will defer to @ekiwi if he wants more or less branches available for backporting.

Update master for 0.5.0 release

---

src/main/scala/chiseltest/formal/package.scala
src/main/scala/chiseltest/formal/vips/MagicPacketTracker.scala
src/test/scala/chiseltest/formal/MagicPacketTrackerTests.scala

This re-usable VIP has proven to be pretty useful for verifying various FIFOs.

formal: add MagicPacketTracker VIP

---

src/main/scala/chiseltest/formal/backends/smt/SMTExprEval.scala
src/test/scala/chiseltest/formal/backends/smt/SMTExprEvalSpec.scala

Add signed div, rem and mod in SMTExprEval.
This will fix #508

formal: deal with signed division in SMTExprEval

---

.github/workflows/test.yml
src/main/scala/chiseltest/formal/backends/Maltese.scala
src/main/scala/chiseltest/formal/backends/smt/CompactSmtEncoding.scala
src/main/scala/chiseltest/formal/backends/smt/SMTLibResponseParser.scala
src/main/scala/chiseltest/formal/backends/smt/SMTLibSolver.scala
src/main/scala/chiseltest/formal/backends/smt/SMTModelChecker.scala
src/main/scala/chiseltest/formal/backends/smt/Solver.scala
src/main/scala/chiseltest/formal/backends/smt/UnrollSmtEncoding.scala
src/main/scala/chiseltest/formal/package.scala
src/test/scala/chiseltest/formal/FormalBackendOption.scala

This will be ready to merge once the final bug in `bitwuzla` has been fixed:  https://github.com/bitwuzla/bitwuzla/issues/35

formal: add support for bitwuzla solver

---

src/main/scala/chiseltest/experimental/Observe.scala
src/main/scala/chiseltest/formal/past.scala
src/main/scala/chiseltest/formal/vips/MagicPacketTracker.scala
src/main/scala/chiseltest/simulator/jna/JNAUtils.scala
src/test/scala/chiseltest/backends/verilator/VerilatorClockPokeTest.scala
src/test/scala/chiseltest/formal/examples/SvaDemos.scala
src/test/scala/chiseltest/formal/examples/VGBComparisonOfFormalAndSimulation.scala
src/test/scala/chiseltest/iotesters/AggregateOrderingSpec.scala
src/test/scala/chiseltest/tests/ChiselEnumTest.scala

This fixes some breakage from: https://github.com/chipsalliance/chisel3/pull/2758

remove use of deprecated functions

---

build.sbt

do not warn about firrtl imports

---

.github/workflows/setup-oss-cad-suite/action.yml
.github/workflows/test.yml

This is inspired by the changes made in the
chisel3 CI and should be less flaky.

Use our own action to setup the OSS CAD tools

---

build.sbt

https://github.com/ucb-bar/firrtl2/releases/tag/v5.0.0

switch to the latest firrtl2 release

---

build.sbt

With lots of inspiration from the firrtl build.sbt.

modernize build.sbt

---

LICENSE
LICENSE.contributors
README.md

I am not a lawyer and history is murky. So I did my best to follow the CLA that every contributor has to sign.

Add License File
