ucb-bar/chiseltest

src/main/scala/chisel3/tester/TreadleBackend.scala

This PR fixes an issue where new/updated annotations from the [initial compiler pass](https://github.com/ucb-bar/chisel-testers2/blob/master/src/main/scala/chisel3/tester/TreadleBackend.scala#L233) are not passed to the [following lowering pass](https://github.com/freechipsproject/treadle/blob/master/src/main/scala/treadle/executable/ExecutionEngine.scala#L430).
Related: https://github.com/freechipsproject/chisel3/issues/968

Preserve annotations from initial FIRRTL pass

---

src/main/scala/chisel3/tester/BackendInterface.scala
src/main/scala/chisel3/tester/ChiselScalatestTester.scala
src/main/scala/chisel3/tester/DecoupledDriver.scala
src/main/scala/chisel3/tester/ThreadedBackend.scala
src/main/scala/chisel3/tester/TreadleBackend.scala
src/main/scala/chisel3/tester/package.scala
src/test/scala/chisel3/tests/FaultLocatorTest.scala
src/test/scala/chisel3/tests/RegionsTest.scala

Resolves #18 
- Remove blocking `region(...) { ... }` API, regions now declared with `fork.withRegion(...) { ... }`.
- Add `.joinAndStep(clock)` API to allow threads to join on another that usually executes afterward in the cycle. This structurally enforces that the thread cannot go back in time, but schedules it to run on a future timeslot.
- Support tracing (source line fault locator on a failed expect) across threads, going up parent forks.

Fork with Regions

---

src/main/scala/chisel3/tester/experimental.scala
src/test/scala/chisel3/tests/AsyncResetRegTest.scala

- brings code here in line with Treadle changes to fix this special case
- only issue when async-registers hooked up like a flip-flop

Fix Problem AsyncResetExample

---

src/main/scala/chisel3/tester/ChiselScalatestTester.scala
src/main/scala/chisel3/tester/RawTester.scala
src/main/scala/chisel3/tester/TreadleBackend.scala
src/main/scala/chisel3/tester/experimental/TestOptionBuilder.scala
src/main/scala/chisel3/tester/experimental/UncheckedClockPoke.scala
src/main/scala/chisel3/tester/experimental/package.scala
src/main/scala/chisel3/tester/internal/BackendInterface.scala
src/main/scala/chisel3/tester/package.scala
src/test/scala/chisel3/tests/AsyncResetRegTest.scala
src/test/scala/chisel3/tests/ClockPokeTest.scala

Resolves #29 
Perhaps unsurprisingly, this also went deep down the refactor rabbit hole.
- Refactors `run(dutGen => T)` to return a TestBuilder, which can be chain applied to run a test.
- Adds an experimental implicit conversion on the ChiselScalatestTester TestBuilder to allow `.withExecOptions`, `.withTesterOptions`. See the AsyncResetRegTest for an usage example.
- Removes the `run(dutGen, execOptions)` methods, so you have to import experimental to specify options.
- Note: TestBuilder is not provided for RawTester (so there's no way to specify execution options / tester options there). But the primary use for that is probably simple examples, where you probably don't need this power anyways. If this is wrong (as in you have a legit use case), I can add a TestBuilder object to …

Add experimental with[Option] to run, high/low() on clock

---

src/test/scala/chisel3/tests/OptionsPassingTest.scala

2.11 scalatest api returns different test context name
than 2.12, this fix checks to make sure a vcd file was created by using less restrictive name checking.

Fix 2.11 test failure

---

src/main/scala/chisel3/tester/backends/BackendExecutive.scala
src/main/scala/chisel3/tester/backends/treadle/TreadleBackend.scala
src/main/scala/chisel3/tester/backends/treadle/TreadleExecutive.scala
src/main/scala/chisel3/tester/defaults.scala
src/main/scala/chisel3/tester/internal/ThreadedBackend.scala

- Re-organize packages
- create backends
- add a treadle backend
- Generalize backends in anticipation of verilator
- create BackendExecutive
- combinational path building should be shared so moved to here.
- new TreadleBackend
- Uses BackendExecutive
- Eliminate try block in object
- Simplifies debugging
- Split out TreadleExecutive from TreadleBackend
- ThreadedBackend
- provides dut access
- this required parameterization of trait with dut's type

Beginning support for Verilator backend.

---

src/main/scala/chisel3/tester/backends/treadle/TreadleExecutive.scala

- Refactor TreadleExecutive to not do that
- Saves time, looks nicer

TreadleBackend elaborates chisel module twice

---

src/main/scala/chisel3/tester/backends/treadle/TreadleExecutive.scala
src/main/scala/chisel3/tester/experimental/TestOptionBuilder.scala
src/test/scala/chisel3/tests/BoreTest.scala
src/test/scala/chisel3/tests/MixedVec.scala
src/test/scala/chisel3/tests/OptionsBackwardCompatibilityTest.scala
src/test/scala/chisel3/tests/VecPokeExpectTest.scala

- Add the low firrtl compiler to TreadleExecutive
- Send hint to treadle so it knows compiled form
- Fix backward compatibility with Driver
- Check compiler type to help figure out the backend
- Backward compatibility only supported for treadle and verilator
- Add boringutils test
- Backward compatibilty requires compile workaround
- Can we just eliminate Driver compatibility mode here???
- Fixed CopyVpiFiles
- looks like this might fail if early file was there but a late one wasn't
- this code came from chisel-testers
- Fix top level test names
- behavior of "Testers2 with Vcs"
- behavior of "Testers2 with Verilator"
- Shortened VCS to just see if a simple circuit will build and simulate.
- in long run we still need mechanism to run an arbitrary test with arbitrary backend

Fix toolchain so treadle supports boringutils

---

build.sbt

Undo broken attempt to convert `defaultVersions` to a Map.

Fix broken Seq -> Map replacement.

---

README.md

Fix external links in README

---

src/main/scala/chisel3/tester/package.scala
src/test/scala/chisel3/tests/BundleLiteralsSpec.scala

It works (I hope). Not sure if Bundle.elements being public is an intended API or if it might be cleaner if we introduced some DataMirror API.

Support Bundle literal peek

---

src/main/scala/chisel3/tester/DecoupledDriver.scala
src/main/scala/chisel3/tester/package.scala
src/test/scala/chisel3/tests/QueueTest.scala

Signed-off-by: shuyun <shuyunjia@outlook.com>
issue related: #89
This commit is to: 
1. support enqueue/dequeue of IrrevocableIO
2. add implicit convert of IrrevocableIO to ReadyValidIO

support enqueue/dequeue of IrrevocableIO

---

src/main/scala/chisel3/tester/ChiselScalatestTester.scala

This adds a missing closing parenthesis in the Scaladoc for `ChiselScalatestTester`.

Fix missing Scaladoc parenthesis

---

README.md
build.sbt

We settled on ChiselTest (with package name `chiseltest`) during the previous chisel-dev meeting. This updates the README to reflect that.
One open question: while the sbt package will be `chiseltest`, the import is still `chisel3.tester`. I'm not sure about whether we want to rename that, and what to rename to. `import chiseltest._`? `import chisel3.test._`? `import chisel3.chiseltest._`? A compatibility shim should allow existing imports to work for a while.
@ucbjrl when this PR goes through, can you also change the repo name to ChiselTest and (maybe? not sure about implications) move it to freechipsproject? Also, is it possible to publish both under sbt package `chisel-testers2` and `chiseltest` for some limited migration period?

Rename testers2 to ChiselTest

---

src/main/scala/chiseltest/ChiselScalatestTester.scala

Was somehow removed in the stage/phase refactor in https://github.com/ucb-bar/chisel-testers2/commit/cbfe5b647e0baf1b5e4923109974e757d3e55059 - not sure if intentional. But this adds it back.
Tested with both treadle and Verilator.

Re-add -DwriteVcd=1 feature

---

src/main/scala/chiseltest/backends/treadle/TreadleBackend.scala
src/main/scala/chiseltest/internal/BackendInterface.scala
src/main/scala/chiseltest/legacy/backends/verilator/VerilatorBackend.scala
src/main/scala/chiseltest/package.scala
src/test/scala/chiseltest/tests/ChiselEnumTest.scala

Partial for #12
`poke` and `expect` work as expected. `peek` does not, because I don't think there's a programmatic literal construction API for ChiselEnum.
`pokeBits` has been expanded to Data in general. I'm not sure if this is the right solution (alternatively, ChiselEnum can be Bits - because it's very Bits-like). While expanding the pokeBits API makes it work on things like Clock (and eliminates the need for a pokeClock API) it becomes less type safe (should pokeBits be allowed on Bundle? probably not - that is handled at a higher level). Alternatives include pokeElement (but that wouldn't work on Analog), or overloading pokeBits to support Bits, Clock, and ChiselEnum.

ChiselEnum support

---

src/main/scala/chiseltest/ChiselScalatestTester.scala
src/main/scala/chiseltest/experimental/ChiselTestShell.scala
src/main/scala/chiseltest/experimental/TestOptionBuilder.scala
src/test/scala/chiseltest/experimental/tests/VerilatorBasicTests.scala
src/test/scala/chiseltest/tests/OptionsPassingTest.scala

The major case for this is that command line arguments have a better discovery mechanism through `--help`
- Add ChiseTestShell that can parse command line arguments and produce corresponding annotations
- Adds helper method `withFlags` that is the equivalent for CLI flags as `withAnnotations`
- Slight refactoring of TestBuilder to be a trait with two implementations AnnotatedTestBuilder and FlaggedTestBuilder
- Changed experimental basic verilator test to use this new way of selecting the verilator backend

Adds the ability to invoke tests with command line arguments

---

src/main/scala/chiseltest/legacy/backends/verilator/VerilatorExecutive.scala

Currently verilator backend runs `chisel3.stage.phases.Elaborate` twice, first one is generating circuit, second is generating verilog.
In first elaborate phase will leave `chisel3.internal.Builder` to a wrong state, which leads to second elaborate phase throw a exception "attempted to instantiate a Module, but nothing happened".

Bug fix for verilator backend

---

src/main/scala/chiseltest/ChiselScalatestTester.scala
src/main/scala/chiseltest/experimental/TestOptionBuilder.scala
src/test/scala/chiseltest/tests/OptionsPassingTest.scala

- Calls to .withFlags and .withAnnotations now keeps values from previous invocations
- removed unused logger import
- made flags and annos vals in TestBuilder so they can be retained for subsequent .with* invocations
- updated scaladoc on `def test` to mention withFlags
- Fixed `it should "allow specifying configuration options using annotations and CLI style flags"` test
- It needed all three output file annotations to make a test run directory with consistently named files

Fix CI testing problem with OptionsPassingTest

---

src/main/scala/chiseltest/ChiselScalatestTester.scala
src/main/scala/chiseltest/internal/Testers2.scala
src/main/scala/chiseltest/legacy/backends/vcs/CopyVpiFiles.scala
src/main/scala/chiseltest/legacy/backends/vcs/GenVcsVerilogHarness.scala
src/main/scala/chiseltest/legacy/backends/vcs/VcsAnnotations.scala
src/main/scala/chiseltest/legacy/backends/vcs/VcsBackend.scala
src/main/scala/chiseltest/legacy/backends/vcs/VcsExecutive.scala
src/main/scala/chiseltest/legacy/backends/vcs/VerilogToVcs.scala
src/main/scala/chiseltest/legacy/backends/verilator/VerilatorExecutive.scala
src/test/scala/chiseltest/experimental/tests/VcsBasicTests.scala
src/test/scala/chiseltest/experimental/tests/VerilatorBasicTests.scala

- Create new VcsBackendAnnotation
- Create support utilities for Vcs building tools
- CopyVpiFiles move vpi and header files into place
- GenVcsVerilogHarness  Compile stuff
- VcsAnnotations control behavior of the Vcs backend
- Create VcsBackend, a trivial sub-classing of VerilatorBackend
- Create VcsExecutive
- constructs VcsBackEnd requirements calls the constructor
- Create SimpleVcsTests
- Added String to Uniquify Verilator and Vcs Tests
- Suppress VCS tests if VCS not present in path
- Updates to PR #58
- Fixed CopyVpiFiles
- looks like this might fail if early file was there but a late one wasn't
- this code came from chisel-testers
- Fix top level test names
- behavior of "Testers2 with Vcs"
- behavior of "Testers2 with Verilator"
- Shortened VCS to just see if a simple circuit …

Create VCS backend for testers2

---

.github/scripts/ExtractBuildDependenciesFromPullRequest.gawk
.github/scripts/generateGitClones.gawk
.github/scripts/generateVersionOverrides.gawk
.github/workflows/pr-test.yml

Since no build dependencies are explicitly specified, GitHub will use whatever has been published on maven.

Add support for GitHub workflows.

---

src/main/scala/chiseltest/experimental/UncheckedClockPoke.scala
src/main/scala/chiseltest/package.scala

The double negative actually inverts the error message =(

Fix non-input-poking error message

---

src/main/scala/chiseltest/backends/treadle/TreadleBackend.scala
src/main/scala/chiseltest/internal/BackendInterface.scala
src/main/scala/chiseltest/internal/TestEnvInterface.scala
src/main/scala/chiseltest/legacy/backends/verilator/VerilatorBackend.scala
src/main/scala/chiseltest/package.scala
src/test/scala/chiseltest/tests/FaultDecoderTest.scala

For expect failures, the error now includes the hex value, decimal value, and a type-specific decoding (where applicable).
For example:
- UInt case: `out=42 (0x2a) did not equal expected=0 (0x0)`
- Bool case: `out=true (1, 0x1) did not equal expected=false (0, 0x0)`
- Fixed case: `out=-2.0 (-4, -0x4) did not equal expected=-0.5 (-1, -0x1)`
- Enum case: `out=[unimplemented enum decode] (0, 0x0) did not equal expected=[unimplemented enum decode] (1, 0x1)` (@hngenc, I think StrongEnum needs some kind of reflection API to get the name from a integer? - related: #111)
Architecturally, this passes a decode function through the internals of `wire.expect` -> `BackendInterface.expectBits` -> `TestEnvInterface.testerExpect`. Does not expose any additional APIs. Bundles aren't affected, since the …

Display hex and type-specific values on expect failures

---

src/main/scala/chiseltest/backends/treadle/TreadleExecutive.scala

Necessary to publish up to date snapshot release

TreadleTesterPhase requires `new` now that it is a `class`

---

src/main/scala/chiseltest/experimental/TestOptionBuilder.scala

CompilerAnnotation has been deprecated and is now rarely used in FIRRTL,
replaced with RunFirrtlTransformAnnotation of an Emitter. The
(deprecated) support for ExecutionOptions now handles this change.
https://github.com/freechipsproject/firrtl/pull/1870 necessitates this change. Concretely, `FirrtlExecutionOptions` no longer create `CompilerAnnotation`, instead they create `RunFirrtlTransformAnnotation` with an `Emitter`.

Fix legacy support for ExecutionOptions

---

README.md
src/test/scala/chiseltest/tests/ThreadOrderTest.scala

As described in the title, adds the fork behavior to the README, and a test for it.
Resolves #202

Add thread ordering documentation and supporting test

---

src/main/scala/chiseltest/RawTester.scala

Possible workaround for #209 - doesn't address the versioning issue, but possibly removes one symptom. Not sure if there's a easy way to test this before this gets published.
No idea why it was there in the first place...

Remove scalatest Assertions from RawTester

---

src/main/scala/chiseltest/legacy/backends/vcs/VcsExecutive.scala

``moreVcsFlags` is now used properly when constructing vcs command line
Looks like typo when coverage flags added
@ryan-lund @TsaiAnson can one of you confirm this looks right now, thanks.

Fix probable bug in `VcsExecutive`

---

build.sbt

Fixes problems found in sbt and intellij when using two different versions

Use only a single version of scalatest

---

.gitignore
build.sbt
build.sc

Since Chisel 3.5 recently dropped Scala 2.11 support, there is no point in keeping it in chiseltest.

build: match chisel3 behavior by only building for scala 2.12.13

---

.github/workflows/test.yml

This gives us a more up to date version of verilator and will make things easier to reproduce for people using the latest Ubuntu LTS.

ci: install verilator instead of using a container

---

.github/workflows/test.yml
src/main/scala/chiseltest/package.scala
src/test/scala/chiseltest/tests/BundleLiteralsSpec.scala
src/test/scala/chiseltest/tests/VecLiteralsSpec.scala

Depends on chipsalliance/chisel3#1834
Extends literal handling API with
- package object chiseltest
- implicit class testableVec[T <: Vec[_]](x: T)
- def pokePartial(value: T): Unit
- def expectPartial(value: T): Unit
Include VecLiteralsSpec for tests

Add Support for using Vec literals

---

src/test/scala/chiseltest/coverage/SimulatorCoverageTest.scala

This is in response to: https://github.com/chipsalliance/chisel3/pull/1891

test: cover statements are new reset guarded by chisel and thus the counts are one less

---

src/main/scala/chiseltest/legacy/backends/verilator/Utils.scala
src/main/scala/chiseltest/legacy/backends/verilator/VerilatorExecutive.scala

All binaries, object files, C++ files, Makefiles, etc generated by Verilator are kept in a "verilated" subfolder and deleted before execution of a new test.

Verilator generated artifacts is a subfolder

---

build.sbt
src/main/scala/chiseltest/internal/Testers2.scala
src/main/scala/chiseltest/legacy/backends/verilator/VerilatorExecutive.scala
src/test/scala/chiseltest/experimental/tests/VerilatorCachingTests.scala

Adds a CachingAnnotation which enables binary reuse across verilator test runs if high FIRRTL, elaborated annotations, and underlying versions match. In testing reduces the VerilatorBasicTests runtime from 35 seconds on first run to 5 seconds on second (cached) run.
Addresses: https://github.com/ucb-bar/chisel-testers2/issues/106 and https://github.com/ucb-bar/chisel-testers2/issues/212

Add binary reuse to Verilator tests via annotation

---

src/test/scala/chiseltest/backends/verilator/VerilatorCachingTests.scala

This ensures that it will be included in the verilator regression tests that run on all supported versions.

move verilator caching test to verilator specific directory

---

src/main/scala/chiseltest/legacy/backends/verilator/VerilatorExecutive.scala

I had made a stupid mistake in #308 and used `equals` for comparing hashes, which is object comparison not the content, and will always fail on two separate arrays, even if their contents are the same. The original code in #267 also used `==` which I believe is an alias for `equals`, and therefore never worked either.
That probably why I never got `CachingAnnotation` to work :)
It seems there are currently no tests checking for effectiveness of `CachingAnnotation`, or if they are they don't seem to be working.

Fix comparison of hashes for `CachingAnnotation`

---

src/test/scala/chiseltest/coverage/SimulatorCoverageTest.scala

This renames affected names to what is being seen now.

Changes to chisel have affected coverage names

---

src/main/scala/chiseltest/internal/Testers2.scala
src/main/scala/chiseltest/legacy/backends/vcs/VcsAnnotations.scala
src/main/scala/chiseltest/legacy/backends/vcs/VcsBackend.scala
src/main/scala/chiseltest/legacy/backends/vcs/VcsExecutive.scala
src/main/scala/chiseltest/legacy/backends/verilator/VerilatorExecutive.scala
src/test/scala/chiseltest/backends/verilator/VerilatorCachingTests.scala
src/test/scala/chiseltest/backends/verilator/VerilatorCoverageTests.scala
src/test/scala/chiseltest/experimental/tests/VcsCoverageTests.scala

If the user wants to rely on the simulator built-in Verilog coverage, they can directly supply the relevant flags to the simulator.
I talked to @vighneshiyer and he is OK removing this as it isn't a very clean API.
I improved the Verilator tests to actually check that an appropriate coverage file is generated.

remove simulator specific Verilog coverage flags

---

src/main/scala/chiseltest/simulator/ipc/IPCSimulatorContext.scala

Otherwise there might be errors trying to resolve the overloaded put method.
This is addressing the issue observed by @sequencer

simulator: explicitly convert argument to bytes

---

src/main/scala/chiseltest/simulator/Simulator.scala
src/main/scala/chiseltest/simulator/TreadleSimulator.scala

Only supported in treadle for now!
This feature is needed for the `iotesters` compatibility PR as well as for the formal verification PR.

simulator: add minimal peek/poke support for memories

---

src/main/scala/chiseltest/simulator/Compiler.scala

This ensures more isolation between different phases in the compilation process.
E.g. when we set the log level for compiling to LoFirrtl it should not leak into the compilation
to Verilog.

simulator: extends the number of annotations that should be removed

---

.github/workflows/test.yml
build.sbt
build.sc
src/main/scala/chiseltest/ChiselScalatestTester.scala
src/main/scala/chiseltest/ChiselUtestTester.scala
src/main/scala/chiseltest/RawTester.scala
src/main/scala/chiseltest/formal/AddResetAssumptionPass.scala
src/main/scala/chiseltest/formal/Formal.scala
src/main/scala/chiseltest/formal/backends/FlattenPass.scala
src/main/scala/chiseltest/formal/backends/Maltese.scala
src/main/scala/chiseltest/formal/backends/Trace.scala
src/main/scala/chiseltest/formal/package.scala
src/main/scala/chiseltest/internal/TestEnvInterface.scala
src/main/scala/chiseltest/simulator/Compiler.scala
src/test/scala/chiseltest/formal/BasicBoundedCheckTests.scala
src/test/scala/chiseltest/formal/FormalTag.scala
src/test/scala/chiseltest/formal/MemoryTests.scala
src/test/scala/chiseltest/formal/ResetAssumptionTests.scala
src/test/scala/chiseltest/formal/backends/FirrtlBmcTests.scala
src/test/scala/chiseltest/simulator/ComplianceTest.scala
src/test/scala/chiseltest/utils/FlatSpecWithTargetDir.scala

This PR adds some fundamental formal verification support.
A user needs to:
1) add `with Formal` to their `ChiselScalatestTester` derived testing class
2) call `verify` with a verification operation
So for a simple bounded check the syntax is:
```.scala
verify(new Dut, Seq(BoundedCheck(kMax = 1)))
```
Public Annotations included in this PR:
- `Z3EngineAnnotation`: use Z3 for model checking (default)
- `CVC4EngineAnnotation`: use CVC4 for model checking
- `BoundedCheck`: the only verification op so far, but could be extended with something like `KInduction`
- `ResetOption`: by default the formal backend will drive the reset pin high for at least one cycle in the beginning of the check; `ResetOption(0)` will remove any constraints from the reset pin, `ResetOption(3)` will enforce a reset …

Minimal Formal Verification Support

---

.github/workflows/test.yml
src/test/scala/chiseltest/backends/verilator/VerilatorBasicTests.scala
src/test/scala/chiseltest/backends/verilator/VerilatorCachingTests.scala
src/test/scala/chiseltest/backends/verilator/VerilatorClockPokeTest.scala
src/test/scala/chiseltest/backends/verilator/VerilatorCoverageTest.scala
src/test/scala/chiseltest/backends/verilator/VerilatorCoverageTests.scala
src/test/scala/chiseltest/backends/verilator/VerilogBlackBoxTest.scala
src/test/scala/chiseltest/coverage/SimulatorCoverageTest.scala
src/test/scala/chiseltest/experimental/tests/NegativeInputValuesTest.scala
src/test/scala/chiseltest/simulator/ComplianceTest.scala
src/test/scala/chiseltest/simulator/Icarus.scala
src/test/scala/chiseltest/simulator/MemoryCompliance.scala
src/test/scala/chiseltest/simulator/Verilator.scala
src/test/scala/chiseltest/tests/VerilogBlackBoxTests.scala

This also cuts down on the number of `mac` jobs we run because those machines seem to be harder to get.

ci: reorganize into more independent jobs

---

src/main/scala/chiseltest/internal/BackendExecutive.scala
src/main/scala/chiseltest/internal/Testers2.scala
src/main/scala/chiseltest/simulator/DebugPrintWrapper.scala
src/test/scala/chiseltest/internal/PrintPeekPokeTest.scala

Some convenient functionality that I recently used to track down a bug. Might come in handy to others and it is part of the `internal` package, so it won't increase our public API surface.

internal: add PrintPeekPoke annotation for debugging

---

src/main/scala/chiseltest/formal/AddResetAssumptionPass.scala
src/main/scala/chiseltest/formal/FirrtlUtils.scala
src/main/scala/chiseltest/formal/past.scala
src/main/scala/chiseltest/simulator/TreadleSimulator.scala
src/test/scala/chiseltest/formal/MemoryTests.scala
src/test/scala/chiseltest/formal/SafePastSpec.scala
src/test/scala/chiseltest/formal/examples/DecoupledGCD.scala
src/test/scala/chiseltest/formal/examples/KeepMax.scala
src/test/scala/chiseltest/formal/examples/SvaDemos.scala
src/test/scala/chiseltest/formal/examples/VGBComparisonOfFormalAndSimulation.scala
src/test/scala/chiseltest/formal/examples/ZipCpuQuizzes.scala

This allows users to write assertions/assumptions about past values without having to manually keep track of whether they are valid or not. An automated analysis pass figures out the maximum `Past` delay and delays the assertion for the right amount of cycles after reset.

formal: add a past(..., N) function for assert/assume statements

---

build.sbt
build.sc
src/main/scala/chiseltest/formal/backends/IsModelChecker.scala
src/main/scala/chiseltest/formal/backends/Maltese.scala
src/main/scala/chiseltest/formal/backends/TransitionSystemSimulator.scala
src/main/scala/chiseltest/formal/backends/smt/SMTExprEval.scala
src/main/scala/chiseltest/formal/backends/smt/SMTLibResponseParser.scala
src/main/scala/chiseltest/formal/backends/smt/SMTLibSolver.scala
src/main/scala/chiseltest/formal/backends/smt/SMTModelChecker.scala
src/main/scala/chiseltest/formal/backends/smt/Solver.scala
src/test/scala/chiseltest/formal/backends/smt/SMTLibResponseParserSpec.scala
src/test/scala/chiseltest/formal/backends/smt/Z3SolverSpec.scala

Together with an overhaul of the smt expression library in firrtl, this lets us get rid of the dependency on maltese-smt.
This PR depends on: https://github.com/chipsalliance/firrtl/pull/2350

formal: implement our own smt solver bindings + checker

---

src/main/scala/chiseltest/formal/backends/Maltese.scala
src/main/scala/chiseltest/formal/backends/smt/SMTLibSolver.scala
src/main/scala/chiseltest/formal/backends/smt/SMTModelChecker.scala
src/main/scala/chiseltest/formal/backends/smt/Solver.scala
src/test/scala/chiseltest/formal/backends/smt/Z3SolverSpec.scala

This is similar to the Simulator/SimulatorContext split and allows us to properly terminate solvers running in the background at the end of a model checking run.
Fixes #392

formal: split Solver into Solver/SolverContext

---

src/main/scala/chiseltest/internal/GenericBackend.scala
src/test/scala/chiseltest/coverage/SimulatorCoverageTest.scala
src/test/scala/chiseltest/experimental/tests/AssertTest.scala

Fixes problem where assert fires due to exiting of default timescope
Fixed couple of nits to make code clean.

Remove final step from generic backend main loop.

---

src/main/scala/chiseltest/exceptions.scala
src/main/scala/chiseltest/internal/GenericBackend.scala
src/main/scala/chiseltest/simulator/DebugPrintWrapper.scala
src/main/scala/chiseltest/simulator/Simulator.scala
src/main/scala/chiseltest/simulator/TreadleSimulator.scala
src/main/scala/chiseltest/simulator/VerilatorSimulator.scala
src/main/scala/chiseltest/simulator/ipc/IPCSimulatorContext.scala
src/main/scala/chiseltest/simulator/jna/JNASimulatorContext.scala
src/main/scala/chiseltest/simulator/jna/JNAUtils.scala
src/main/scala/chiseltest/simulator/jna/VerilatorCppJNAHarnessGenerator.scala
src/test/scala/chiseltest/simulator/Icarus.scala
src/test/scala/chiseltest/simulator/StopAssertAssumeCompliance.scala
src/test/scala/chiseltest/simulator/Treadle.scala
src/test/scala/chiseltest/simulator/Verilator.scala
src/test/scala/chiseltest/tests/AssertTests.scala

Turns out that we never had any tests for what should happen if a stop becomes active during a test.
This PR is trying to design a spec for the `Simulator` interface for what should happen if a stop, assert or assume fires.

  simulator: define common API for stop/assert/assume interrupts 

---

src/main/scala/chiseltest/experimental/Observe.scala
src/test/scala/chiseltest/experimental/tests/ObserveExposeTest.scala
src/test/scala/chiseltest/experimental/tests/ObserveTest.scala
src/test/scala/chiseltest/formal/examples/DecoupledGCD.scala
src/test/scala/chiseltest/formal/examples/VGBComparisonOfFormalAndSimulation.scala

This PR adds the Observer trait that can be used on wrapper modules for looking into submodules on chiseltest.
The wrapper makes sure the observed objects are only created in the object instantiation during the test and not Verilog generation (creating the observed wires).
Create a Chisel module that instantiates a submodule as usual:
```scala
import chisel3._
// This is the module and submodule to be tested
class SubModule extends Module {
val reg  = Reg(UInt(6.W))
reg := 42.U
}
// Top module which instantiates the submodule
class Top extends Module {
val submodule = Module(new SubModule)
}
// Generate the main project Verilog
object Proj extends App {
(new chisel3.stage.ChiselStage).emitVerilog(
new Top()
)}
```
In the test, wrap the top module adding the `Observer` trait and inside it …

Add Observer trait and function for Boringtools submodule drilling

---

src/main/scala/chiseltest/formal/backends/smt/SMTLibSolver.scala
src/main/scala/chiseltest/formal/backends/smt/Solver.scala

This is in preparation of a constrained random implementation.
@vighneshiyer and I are working on the actual sampler out of tree, but we need this method in `chiseltest` so that we can re-use the SMT solver bindings.

formal: add softAssert method to solver

---

src/main/scala/chiseltest/simulator/VcsSimulator.scala

The path to the simulator binary and the waveform was updated to work when running the simulation from os.pwd.
@jiegec, could you please check if this fixes your issue? This PR should address the wrong binary path as well as the misplaced wave dump.

vcs: run binary from os.pwd

---

src/main/scala/chiseltest/formal/Formal.scala
src/main/scala/chiseltest/formal/backends/Maltese.scala

For the examples that we have in the repo, the SMT solving isn't really getting any faster, but the SMT files we generate are somewhat smaller. For a bigger example (ShapeProcessorProps.smt2) it goes from 114K to 57K.
This PR also adds an escape hatch annotation in case the optimizations turn out not to be a good idea, but I think they should be on by default.

formal: run firrtl optimizations before generating STMLib

---

src/main/scala/chiseltest/formal/backends/Maltese.scala
src/test/scala/chiseltest/formal/BasicBoundedCheckTests.scala

Previously it was running into an assertion violation.

formal: if there are no asserts, the verification needs to pass

---

src/test/scala/chiseltest/tests/HardwareTestsTest.scala

this ports the tests from https://github.com/ucb-bar/chisel-testers2/pull/444

hardware: add more timeout tests for treadle and verilator

---

.github/workflows/test.yml
src/main/scala/chiseltest/formal/backends/Maltese.scala

This avoids file serialization which results in "Multiple
CustomFileEmission annotations would be serialized to the same file"
exceptions sometimes.
I believe this is a real bug that used to be hidden but was exposed by https://github.com/chipsalliance/firrtl/pull/2393.
That being said, the error is annoying so at least for 3.5 I'm going to change file emission to only warn if the colliding contents are identical.
This PR also fixes the Verilator CI tests on MacOS.
The issue is fixed by installing an older version of Verilator via Homebrew.
It's unfortunately a little slow because it builds from source. We badly need to fix CI, we can speed it up in a follow on PR.

Use FirrtlPhase instead of FirrtlStage in Maltese

---

src/main/scala/chiseltest/formal/backends/FlattenPass.scala
src/main/scala/chiseltest/formal/backends/Maltese.scala
src/test/scala/chiseltest/formal/UndefinedValuesTests.scala

A translation step was missing. This addresses: https://github.com/ucb-bar/chisel-testers2/issues/460

formal: fix replay for DefRandom nodes inside of submodules

---

.gitignore
src/main/scala/chiseltest/package.scala
src/main/scala/chiseltest/simulator/Simulator.scala
src/main/scala/chiseltest/simulator/VcsSimulator.scala
src/main/scala/chiseltest/simulator/ipc/VpiVerilogHarnessGenerator.scala
src/test/scala/chiseltest/simulator/WaveformCompliance.scala

I added support for dumping FSDB waveform used by Synopsys Verdi
Local test passed: `sbt "testOnly chiseltest.simulator.VcsWaveformCompliance"`
gcc version: `gcc version 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC)`
vcs version: `VCS S-2021.09-SP1`
verdi version: `S-2021.09-SP1`

Support FSDB (Verdi) waveform dump

---

src/main/scala/chiseltest/simulator/VcsSimulator.scala
src/main/scala/chiseltest/simulator/ipc/VpiVerilogHarnessGenerator.scala

Three VCS warnings are removed
1. Remove `-none` when no waveform annotation is given, `-none` is not a valid VCS option
```
Warning-[RT_UO] Unsupported option
Unsupported option '-none' is ignored
```
2. Replace `debug_pp` per VCS suggested
```
Warning-[DEBUG_DEP] Option will be deprecated
The option '-debug_pp' will be deprecated in a future release.  
Please use '-debug_acc+pp+dmptf -debug_region+cell+encrypt' instead.
```
3. Reposition `dumpvars` per IEEE Standard
```
Warning-[TFX-DUMPVARCA] DumpVar called previously
As $dumpvars was called in previous time step, ignoring this call.$dumpfile at time #1000
Please refer to section 18.1.2 in the IEEE Verilog Standard 1364-2001 for details on $dumpvars.
```
Local UnitTest Passed: `sbt "testOnly chiseltest.simulator.VcsWaveformCompliance"` …

Remove VCS warning

---

src/main/scala/chiseltest/formal/backends/TransitionSystemSimulator.scala

I have an example right now, where one simulation replay seems to fail, while another succeeds. This means that there is a bug in `chiseltest` which I have not yet been able to find. However, for normal users, I believe it would be better for them to be able to continue without an exception terminating their test.

formal: demote simulation/formal mismach to a warning

---

src/main/scala/chisel3/tester/package.scala
src/test/scala/chiseltest/experimental/tests/AssertTest.scala

This will allow us to remove the package for good after the next release.

deprecate chisel3.testers package

---

src/main/scala/chiseltest/formal/backends/Maltese.scala
src/test/scala/chiseltest/formal/MemoryTests.scala

This might help with https://github.com/ucb-bar/chiseltest/issues/466

formal: test non power of two memories and fix replay bug

---

src/main/scala/chiseltest/internal/BackendInterface.scala
src/main/scala/chiseltest/internal/GenericBackend.scala
src/main/scala/chiseltest/internal/SingleThreadBackend.scala
src/main/scala/chiseltest/internal/TestEnvInterface.scala
src/main/scala/chiseltest/package.scala
src/test/scala/chiseltest/coverage/SimulatorCoverageTest.scala
src/test/scala/chiseltest/tests/FixedPointTests.scala
src/test/scala/chiseltest/tests/GroundTypeTests.scala
src/test/scala/chiseltest/tests/IntervalTests.scala

Note: for `Interval` and `FixedPoint` I decided to just make sure that we get all the features from the old PeekPokeTester API.

Scala type peek poke

---

.github/workflows/test.yml
src/main/scala/chiseltest/simulator/BlackBox.scala
src/main/scala/chiseltest/simulator/VerilatorSimulator.scala
src/main/scala/chiseltest/simulator/jna/JNAUtils.scala
src/main/scala/chiseltest/simulator/jna/VerilatorCppJNAHarnessGenerator.scala
src/test/scala/chiseltest/simulator/Verilator.scala

According to [Spinal HDL documentation](https://spinalhdl.github.io/SpinalDoc-RTD/dev/SpinalHDL/Simulation/install/Verilator.html), Verilator can be used on Windows via MSYS2. But the executable on Windows is `verilator_bin` (see [here](https://github.com/SpinalHDL/SpinalHDL/blob/8631157de28920e6e50854a62f15aaebf52adc62/sim/src/main/scala/spinal/sim/VerilatorBackend.scala#L477)), we need to check the OS to get the correct name.

Support Verilator backend on Windows

---

build.sc

Begin from mill-0.9.7, testFrameworks targets is deperecated, which
cause 'mill bloopInstall' fail to run.
some logs from .metals/metals.log befor this fix:
```
2022.03.25 19:43:09 INFO  [463/1252] chiseltestCrossModule.test.testFramework
2022.03.25 19:43:09 INFO  1 targets failed
2022.03.25 19:43:09 INFO  chiseltestCrossModule.test.testFramework Since mill after-0.9.6 only one test framework per TestModule is supported. Target testFrameworks is deprecated. Please use target testFramework or use on of the predefined TestModules: TestNg, Junit, Scalatest, ...
2022.03.25 19:43:10 INFO  time: ran 'mill bloopInstall' in 10m1s
2022.03.25 19:43:10 ERROR Mill command failed: /tmp/metals17868073092207274821/millw --mill-version 0.9.9 --predef /tmp/metals17868073092207274821/predef.sc …
```

Fix build.sc to avoid testFrameworks

---

src/main/scala/chiseltest/internal/BackendInterface.scala
src/main/scala/chiseltest/internal/GenericBackend.scala
src/main/scala/chiseltest/internal/SingleThreadBackend.scala
src/main/scala/chiseltest/package.scala
src/test/scala/chiseltest/tests/GetStepCountTest.scala

I want to see what other people think. Personally I have developed a fairly strong preference for naming the functionality `getStepCount` instead of `getStep` in order to make it more clear what it is doing.

rename getStep to getStepCount

---

README.md

Missing an r so the link fails.

Fix Verilator link in README

---

src/main/scala/chiseltest/exceptions.scala
src/main/scala/chiseltest/internal/GenericBackend.scala
src/main/scala/chiseltest/internal/SingleThreadBackend.scala
src/test/scala/chiseltest/tests/BasicTest.scala

For Modules with internal signals when the `GenericBackend` goes to peek, the signal will not be found.  This results in a slightly unintuitive `java.util.NoSuchElementException`.
```scala
class dummy extends Module {
val unseen = Reg(UInt(6.W))
unseen := 42.U
}
```
The following test on the above Module throws java.util.NoSuchElementException: key not found exception
```scala
test(new dummy) { c =>
c.unseen.expect(42.U)
}
```
The proposal is to add an `UnpeekableException` which suggests the user use `chiseltest.experimental.expose`. 
The exception message now reads:
```sh
[info]  chiseltest.UnpeekableException: Signal not found. Perhaps you're peeking a non-IO signal. 
[info]  If so, consider using the chiseltest.experimental.expose API.
```
---
As an aside:
- The repetitive code makes …

[GenericBackend] Add `UnpeekableException` if signal not found

---

src/main/scala/chiseltest/simulator/IcarusSimulator.scala
src/test/scala/chiseltest/backends/icarus/IcarusBlackBoxTest.scala

Leveraged the existing work for the Verilator `+plusarg` support to also extend to Icarus Verilog. I don't currently have a VCS license on my personal machine, so I don't have a way to validate VCS. Will see if I can add the same to VCS.
Added an Icarus Verilog test which will test the `+plusarg` functionality. This is also a clone of the `VerilogBlackBoxTest` that is used for Verilator.

added +plusarg support for Icarus

---

src/main/scala/chiseltest/simulator/jna/VerilatorCppJNAHarnessGenerator.scala
src/test/scala/chiseltest/backends/icarus/IcarusTimeTaskTest.scala
src/test/scala/chiseltest/backends/verilator/VerilatorTimeTaskTest.scala

Fixes https://github.com/ucb-bar/chiseltest/issues/538
h/t @terpstra for the bug report and fix
I'm not sure how this happens but you can see my comment in the test about some really bizarre behavior that made writing this test take forever. Basically I originally had:
```scala
behavior of "Verilator backend"
```
When running the test it would correctly generate Verilog and invoke Verilator to create a simulation binary, but `c.out` always returned `0` no matter what I did and any assertions or printfs inside the design were ignored. Merely changing the String "Verilator backend" to anything else fixed the issue.
I feel like I'm taking crazy pills but maybe there's some crazy interaction going on in the ScalaTest harness.

Fix verilator time

---

src/main/scala/chiseltest/simulator/VerilatorSimulator.scala

This will change varilator make to run on a fixed number of jobs. Specificly the number of cores in the computer.
From the `make` manual,
> If the -j option is given without an argument, make  will  not  limit the number of jobs that can run simultaneously.
This behavior was causing my computer to swap a lot.

Verilator make with fixed number of jobs

---

src/main/scala/chiseltest/simulator/ipc/VpiVerilogHarnessGenerator.scala

The 'reset' signal cannot glitch from 0 to 1 at power on.
If it does, then all the assertions in a vcs design will fire.

Fix vcs assertions

---

src/main/resources/simulator/vpi.h

VCS (version Q-2020.03) integration with chiseltest fails with a compiler error when compiling vpi.cpp. It seems that `nullptr` is not defined. Everywhere else, `NULL` seems to be used for the same thing. I made that change and now all my tests in [chisel-pla](https://github.com/stevenmburns/chisel-pla) work with `treadle`, `verilator` and now `vcs`.
I don't know your testing strategy for VCS because it is not an open source tool. Let me know if you would like me to run any tests on `main` against these changes.

VCS Q-2020.03 (at least) fails because it can't find nullptr

---

src/main/resources/simulator/vpi.h
src/main/scala/chiseltest/simulator/VcsSimulator.scala

This is the real fix for the issue addressed in PR #572 
The reason for the `nullptr` not being found compiler error was that the `-std=c++11` flag was not being seen by an older compiler (gcc 4.8.5). What was actually being run was the command line:
```
g++ -w  -pipe -fPIC "-ICS_HOME/include -I/nfs/site/disks/scl.work.50/ash/users/smburns/chisel-examples/test_run_dir/Alu_should_pass_AluSpec_tests -fPIC -std=c++11" -O -I/p/hdk/rtl/cad/x86-64_linux44/synopsys/vcsmx/Q-2020.03/include    -c ../vpi.cpp
```
The double quotes around the command line options in the middle meant that they were not being treated separately, and silently then `-std=c+11` options was being ignored.
The proposed fix corrects this issue, and we can leave the `nullptr` usages in the `vpi.h` file.
Also, the `VcsCFlags` …

Remove quotes around VcsCFlags

---

.github/workflows/test.yml

The Tabby CAD action tends to fail more often than succeed on Mac and there is no bug that we have ever caught with this test.

remove verilator on mac test

---

src/main/scala/chiseltest/exceptions.scala
src/main/scala/chiseltest/internal/TestEnvInterface.scala
src/main/scala/chiseltest/package.scala
src/test/scala/chiseltest/tests/PokeAndExpectPartialTests.scala

This makes partial pokes / expects slightly less broken by implementing them in terms of the normal poke / expect function. One use case that has new tests added and that was definitely somewhat broken is bundles inside of vecs.
This also removes four warnings, which - in this case and afaik - were indicative of a real bug.

partialPoke/Expect: add more tests, improve implementation

---

src/main/scala/chiseltest/simulator/ipc/VpiVerilogHarnessGenerator.scala

This prevents a race condition between the rising clock edge and randomization when RANDOMIZE_DELAY=1. Note that the traditional Chisel randomization delay of #0.002 is based on VCS's default timescale of 1ns/1ps and does not properly work with other timescales. It is much safer to use a full timescale delay, and thus prudent to delay the first rising clock edge till the 2nd time step.
Note that this does change waveforms slightly such that you have a full clock period with no clock before it starts rather than the first rising edge being after merely half a clock-period. See `old` and `new` (except of course there is no zero-time falling edge, I can't figure out how to get rid of it in Wavedrom)

Delay first rising clock edge by 1 half-period in VPI Harness

---

src/main/scala/chiseltest/simulator/ipc/VpiVerilogHarnessGenerator.scala

dumpfile produces a vcd output.
The previous code wrote two streams into the same file.
Replaces https://github.com/ucb-bar/chiseltest/pull/604

vcs: fix vpd generation (#18)

---

src/main/scala/chiseltest/simulator/IcarusSimulator.scala
src/main/scala/chiseltest/simulator/VcsSimulator.scala
src/main/scala/chiseltest/simulator/ipc/IPCSimulatorContext.scala
src/test/scala/chiseltest/simulator/BasicCompliance.scala
src/test/scala/chiseltest/simulator/Icarus.scala
src/test/scala/chiseltest/simulator/PeekPokeCompliance.scala

When using Icarus backend there was many debug messages that was not needed. I changed it to not output anything normally but show debug messages when `SimulatorDebugAnnotation` is set, like the Verilator backend.
By the way I found that some tests in `PeekPokeCompliance` had not properly finished the dut. it was causing the simulator to keep running after the test finished.

Remove Icarus debug messages

---

build.sc

As treadle source code is imported in https://github.com/ucb-bar/chiseltest/commit/a6b1091f66bf58f37855093b314d3d73dae12f23, `treadleModule` should be removed in `build.sc`.

FIX: remove treadleModule in build.sc

---

src/main/scala/chiseltest/internal/BackendExecutive.scala
src/test/scala/chiseltest/tests/OpaqueTypeTest.scala

Addresses #661.
* Remove `getDataNames`
* Add test with `Record` extending `OpaqueType`

Replace getDataNames with DataMirror.fullModulePorts

---

src/main/scala/chiseltest/internal/BackendExecutive.scala
src/test/scala/chiseltest/formal/examples/VGBComparisonOfFormalAndSimulation.scala
src/test/scala/chiseltest/iotesters/examples/ALUTester.scala
src/test/scala/chiseltest/tests/OpaqueTypeTest.scala

Backports #662 to 0.6.x.
* Remove getDataNames
* Add test with Record extending OpaqueType

Replace getDataNames with DataMirror.fullModulePorts (backport to 0.6.x)

---

src/main/scala/chiseltest/internal/PeekPokeTesterBackend.scala
src/test/scala/chiseltest/tests/OpaqueTypeTest.scala

Addresses #661.
Turns out `PeekPokeTester` had the same issue.

Replace getDataNames with DataMirror.fullModulePorts in PeekPokeTester

---

src/main/scala/chiseltest/internal/PeekPokeTesterBackend.scala
src/test/scala/chiseltest/tests/OpaqueTypeTest.scala

Addresses #661.
Backports #667 to 0.6.x branch.

Replace getDataNames with DataMirror.fullModulePorts in PeekPokeTester (backport to 0.6.x)

---

.github/workflows/test.yml

This can lead to us missing some SNAPSHOT updates.

ci: remove sbt caching

---

src/main/scala/treadle2/executable/Memory.scala
src/test/scala/chiseltest/iotesters/examples/LoadMemoryFromFileSpec.scala

Previously, specifying an absolute path in loadMemoryFromFileInline would cause an error when running with treadle, because the path was absolutized using os.path.RelPath. The latter function throws an exception for absolute paths.
Now both absolute and relative paths work (matching the behaviour of Verilator).
Note that this has no security implications, since the previous "relative-path" based implementation also allowed "../../" paths; existing relative paths should not be affected.

Bugfix: loadMemoryFromFile support absolute paths

---

src/main/scala/chiseltest/simulator/ChiselBridge.scala
src/test/scala/chiseltest/regressions/ConvertDecodeTableTest.scala

Closes #697.
The `Booth` module and test is from https://github.com/sequencer/arithmetic/blob/master/arithmetic/src/multiplier/Booth.scala.
Feel free to modify anything.
- ~~Waiting for https://github.com/ucb-bar/firrtl2/pull/29 to be merged~~ (Not necessary)

Add convert DecodeTableAnnotation regression test

---

.github/workflows/test.yml
build.sbt
project/build.properties
project/plugins.sbt
src/main/scala/chiseltest/iotesters/PeekPokeTester.scala
src/main/scala/chiseltest/package.scala
src/main/scala/chiseltest/simulator/ChiselBridge.scala
src/main/scala/chiseltest/simulator/VerilatorCoverage.scala
src/main/scala/chiseltest/simulator/VerilatorSimulator.scala
src/main/scala/treadle2/stage/phases/GetFirrtlAst.scala
src/test/scala/chiseltest/simulator/Verilator.scala
src/test/scala/chiseltest/tests/VecPokeExpectTest.scala
src/test/scala/treadle2/ModuleInLineSpec.scala

Hi,
I'm trying to help with expediating a chiseltest 6.0.0 release as 6.0-SNAPSHOT does not work with the chisel-6.0.0 release.
I also noticed the Verilator coverage support was broken with Verilator versions >= 5.012 (and probably >=5).
Tested only on macOS. All tests (excluding VCS backend, but *including* Verilator, Icarus, and formal) pass. Tests were run as:
`sbt "testOnly chiseltest.** -- -l RequiresVcs"`
Please let me know if any changes are required or otherwise free to make any modifications.
Summary of changes:
- Bumped chisel -> 6.0.0
- Fixed missing (moved) 'Width' class
- Bumped scala -> 2.13.12
- Fixed compilation issues due to 'scala.io' namespace clash
- bump sbt -> 1.9.8
- fix Verilator 5.x coverage
- fix Verilator 5.x tests

Bump to chisel 6 release

---

src/main/scala/chiseltest/formal/Formal.scala
src/main/scala/chiseltest/formal/backends/IsModelChecker.scala
src/main/scala/chiseltest/formal/backends/Maltese.scala
src/main/scala/chiseltest/formal/backends/btor/Btor2ModelChecker.scala
src/main/scala/chiseltest/formal/backends/smt/CompactSmtEncoding.scala
src/main/scala/chiseltest/formal/backends/smt/SMTModelChecker.scala
src/main/scala/chiseltest/formal/backends/smt/UnrollSmtEncoding.scala
src/test/scala/chiseltest/formal/examples/Counter.scala
src/test/scala/chiseltest/formal/examples/ZipCpuQuizzes.scala

Reused much of the BMC code.
- Perform BMC for cycles [0..k-1]
- Asserted constraints for cycles [n..n + k]
- Asserted assumptions for cycles [n..n + k-1]
- Checked the negation of the assertions for cycle n + k
I think I've done much of the initial work to support k-induction for SmtModelCheckers. I believe I initially said I'd support it for btormc first but I was unable to generate a witness for my counter test I introduced which should fail. I have verified that the counter test creates a reasonable witness.
One thing I'm not too sure on is the filtering out of the  `_resetActive` constraint during the inductive step because it does seem like a reasonable constraint that someone could write them self. That said, if  the constraint were present, the search space would be far too …

Add k-induction for SmtModelCheckers 

---

src/main/scala/chiseltest/simulator/IcarusSimulator.scala
src/main/scala/chiseltest/simulator/Utils.scala
src/main/scala/chiseltest/simulator/VerilatorSimulator.scala
src/main/scala/chiseltest/simulator/ipc/IPCSimulatorContext.scala

This PR combines:
* https://github.com/ucb-bar/chiseltest/pull/736
* https://github.com/ucb-bar/chiseltest/pull/737
It changes the default `CFLAGS` for Verilator:
* `-O1` changed to `-Os` as it is a default optimization used by Verilator, and using different ones can result in invalid PCH error ([Verilator OPTs](https://github.com/verilator/verilator/blob/master/include/verilated.mk.in#L129-L136)):
```
cc1plus: error: one or more PCH files were found, but they were invalid
cc1plus: note: use -Winvalid-pch for more information
<command-line>: fatal error: VMockArrayTestbench__pch.h.fast: No such file or directory
compilation terminated.
```
* `-include V$topName.h` removed, as it should not be used according to https://github.com/verilator/verilator/issues/5244#issuecomment-2219960148 …

Fix invalid PCH error
